### ISSUE TITLE
crashes everytime on returning from gallery/camera intent

### ISSUE THREAD

**Issue by kailash09dabhi** [miguelbcr/RxPaparazzo#30]
java.lang.RuntimeException: Unable to start activity ComponentInfo{com.withdirect.mobile/rx_activity_result.HolderActivity}: java.lang.NullPointerException
                                                                           at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2198)
                                                                           at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2257)
                                                                           at android.app.ActivityThread.access$800(ActivityThread.java:139)
                                                                           at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1210)
                                                                           at android.os.Handler.dispatchMessage(Handler.java:102)
                                                                           at android.os.Looper.loop(Looper.java:136)
                                                                           at android.app.ActivityThread.main(ActivityThread.java:5086)
                                                                           at java.lang.reflect.Method.invokeNative(Native Method)
                                                                           at java.lang.reflect.Method.invoke(Method.java:515)
                                                                           at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:785)
                                                                           at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:601)
                                                                           at dalvik.system.NativeStart.main(Native Method)
                                                                        Caused by: java.lang.NullPointerException
                                                                           at rx_activity_result.HolderActivity.onCreate(HolderActivity.java:33)
                                                                           at android.app.Activity.performCreate(Activity.java:5248)
                                                                           at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1110)
                                                                           at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2162)
                                                                           at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2257) 
                                                                           at android.app.ActivityThread.access$800(ActivityThread.java:139) 
                                                                           at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1210) 
                                                                           at android.os.Handler.dispatchMessage(Handler.java:102) 
                                                                           at android.os.Looper.loop(Looper.java:136) 
                                                                           at android.app.ActivityThread.main(ActivityThread.java:5086) 
                                                                           at java.lang.reflect.Method.invokeNative(Native Method) 
                                                                           at java.lang.reflect.Method.invoke(Method.java:515) 
                                                                           at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:785) 
                                                                           at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:601) 
                                                                           at dalvik.system.NativeStart.main(Native Method) 

Hope to hear from you sooon! :)

**Comment by miguelbcr** [comment]
Hi @kailash09dabhi ,
 I'll need a code snippet to see how you are using RxPaparazzo.

**Comment by shashank090789** [comment]
same problem with me while using sample app on samsung galaxy duos.

**Comment by miguelbcr** [comment]
Hi @shashank090789 and @kailash09dabhi ,
I've released [version 0.2.0](https://github.com/miguelbcr/RxPaparazzo/releases/tag/0.2.0)

Sincerely, I don't know if it fixes the error. I've not be able to reproduce the error, but I think it was related with an Ucrop option on the sample app.

Try it out, and let me know if it works for you, If not, I'll appreciate a little more of information about it.

**Comment by miguelbcr** [comment]
Closed due to lack of activity.
Please , feel yourself free to reopen it.

**Comment by sagartrehan** [comment]
I am getting same error. I am updating the library version and let you now if get same crash again.
