### ISSUE TITLE
Fatal exception when I try to take pickture

### ISSUE THREAD

**Issue by ZBlaZe2** [miguelbcr/RxPaparazzo#73]
Here is my code
`RxPaparazzo.single(activity)
.usingCamera()
.subscribeOn(Schedulers.io())
.observeOn(AndroidSchedulers.mainThread())
.subscribe({ response -> 
                        // Do smth
 })`

And stcktrace
`06-12 11:25:51.531 32762-32762/com.ezlo.tracker.debug E/AndroidRuntime: FATAL EXCEPTION: main
                                                                        Process: com.ezlo.tracker.debug, PID: 32762
                                                                        io.reactivex.exceptions.OnErrorNotImplementedException: 1 exceptions occurred. 
                                                                            at io.reactivex.internal.functions.Functions$OnErrorMissingConsumer.accept(Functions.java:704)
                                                                            at io.reactivex.internal.functions.Functions$OnErrorMissingConsumer.accept(Functions.java:701)
                                                                            at io.reactivex.internal.observers.LambdaObserver.onError(LambdaObserver.java:74)
                                                                            at io.reactivex.internal.operators.observable.ObservableObserveOn$ObserveOnObserver.checkTerminated(ObservableObserveOn.java:276)
                                                                            at io.reactivex.internal.operators.observable.ObservableObserveOn$ObserveOnObserver.drainNormal(ObservableObserveOn.java:172)
                                                                            at io.reactivex.internal.operators.observable.ObservableObserveOn$ObserveOnObserver.run(ObservableObserveOn.java:252)
                                                                            at io.reactivex.android.schedulers.HandlerScheduler$ScheduledRunnable.run(HandlerScheduler.java:109)
                                                                            at android.os.Handler.handleCallback(Handler.java:751)
                                                                            at android.os.Handler.dispatchMessage(Handler.java:95)
                                                                            at android.os.Looper.loop(Looper.java:154)
                                                                            at android.app.ActivityThread.main(ActivityThread.java:6119)
                                                                            at java.lang.reflect.Method.invoke(Native Method)
                                                                            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:886)
                                                                            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:776)
                                                                         Caused by: io.reactivex.exceptions.CompositeException: 1 exceptions occurred. 
                                                                            at io.reactivex.internal.operators.observable.ObservableOnErrorNext$OnErrorNextObserver.onError(ObservableOnErrorNext.java:94)
                                                                            at io.reactivex.internal.observers.BasicFuseableObserver.onError(BasicFuseableObserver.java:100)
                                                                            at io.reactivex.internal.operators.observable.ObservableFlatMap$MergeObserver.checkTerminate(ObservableFlatMap.java:495)
                                                                            at io.reactivex.internal.operators.observable.ObservableFlatMap$MergeObserver.drainLoop(ObservableFlatMap.java:331)
                                                                            at io.reactivex.internal.operators.observable.ObservableFlatMap$MergeObserver.drain(ObservableFlatMap.java:323)
                                                                            at io.reactivex.internal.operators.observable.ObservableFlatMap$MergeObserver.onError(ObservableFlatMap.java:288)
                                                                            at io.reactivex.internal.operators.observable.ObservableFlatMap$MergeObserver.checkTerminate(ObservableFlatMap.java:495)
                                                                            at io.reactivex.internal.operators.observable.ObservableFlatMap$MergeObserver.drainLoop(ObservableFlatMap.java:331)
                                                                            at io.reactivex.internal.operators.observable.ObservableFlatMap$MergeObserver.drain(ObservableFlatMap.java:323)
                                                                            at io.reactivex.internal.operators.observable.ObservableFlatMap$MergeObserver.onError(ObservableFlatMap.java:288)
                                                                            at io.reactivex.internal.operators.observable.ObservableFlatMap$MergeObserver.onNext(ObservableFlatMap.java:125)
                                                                            at io.reactivex.internal.operators.single.SingleToObservable$SingleToObservableObserver.onSuccess(SingleToObservable.java:59)
                                                                            at io.reactivex.internal.operators.single.SingleFlatMap$SingleFlatMapCallback$FlatMapSingleObserver.onSuccess(SingleFlatMap.java:111)
                                                                            at io.reactivex.internal.operators.single.SingleJust.subscribeActual(SingleJust.java:30)
                                                                            at io.reactivex.Single.subscribe(Single.java:2703)
                                                                            at io.reactivex.internal.operators.single.SingleFlatMap$SingleFlatMapCallback.onSuccess(SingleFlatMap.java:84)
                                                                            at io.reactivex.internal.operators.observable.ObservableToListSingle$ToListObserver.onComplete(ObservableToListSingle.java:113)
                                                                            at io.reactivex.observers.SerializedObserver.onComplete(SerializedObserver.java:181)
                                                                            at io.reactivex.internal.operators.observable.ObservableConcatMap$SourceObserver.drain(ObservableConcatMap.java:205)
                                                                            at io.reactivex.internal.operators.observable.ObservableConcatMap$SourceObserver.onComplete(ObservableConcatMap.java:148)
                                                                            at io.reactivex.internal.operators.observable.ObservableFlattenIterable$FlattenIterableObserver.onComplete(ObservableFlattenIterable.java:134)
                                                                            at io.reactivex.internal.operators.observable.ObservableBuffer$BufferExactObserver.onComplete(ObservableBuffer.java:134)
06-12 11:25:51.532 32762-32762/com.ezlo.tracker.debug E/AndroidRuntime:     at io.reactivex.internal.operators.observable.ObservableFlatMap$MergeObserver.drainLoop(ObservableFlatMap.java:367)
                                                                            at io.reactivex.internal.operators.observable.ObservableFlatMap$MergeObserver.drain(ObservableFlatMap.java:323)
                                                                            at io.reactivex.internal.operators.observable.ObservableFlatMap$MergeObserver.onComplete(ObservableFlatMap.java:300)
                                                                            at io.reactivex.internal.operators.observable.ObservableFlatMap$MergeObserver.drainLoop(ObservableFlatMap.java:367)
                                                                            at io.reactivex.internal.operators.observable.ObservableFlatMap$MergeObserver.drain(ObservableFlatMap.java:323)
                                                                            at io.reactivex.internal.operators.observable.ObservableFlatMap$MergeObserver.onComplete(ObservableFlatMap.java:300)
                                                                            at io.reactivex.internal.operators.observable.ObservableFromArray$FromArrayDisposable.run(ObservableFromArray.java:110)
                                                                            at io.reactivex.internal.operators.observable.ObservableFromArray.subscribeActual(ObservableFromArray.java:36)
                                                                            at io.reactivex.Observable.subscribe(Observable.java:10842)
                                                                            at io.reactivex.internal.operators.observable.ObservableFlatMap.subscribeActual(ObservableFlatMap.java:55)
                                                                            at io.reactivex.Observable.subscribe(Observable.java:10842)
                                                                            at io.reactivex.internal.operators.observable.ObservableFlatMap.subscribeActual(ObservableFlatMap.java:55)
                                                                            at io.reactivex.Observable.subscribe(Observable.java:10842)
                                                                            at io.reactivex.internal.operators.observable.ObservableBuffer.subscribeActual(ObservableBuffer.java:44)
                                                                            at io.reactivex.Observable.subscribe(Observable.java:10842)
                                                                            at io.reactivex.internal.operators.observable.ObservableFlattenIterable.subscribeActual(ObservableFlattenIterable.java:44)
                                                                            at io.reactivex.Observable.subscribe(Observable.java:10842)
                                                                            at io.reactivex.internal.operators.observable.ObservableConcatMap.subscribeActual(ObservableConcatMap.java:52)
                                                                            at io.reactivex.Observable.subscribe(Observable.java:10842)
                                                                            at io.reactivex.internal.operators.observable.ObservableToListSingle.subscribeActual(ObservableToListSingle.java:58)
                                                                            at io.reactivex.Single.subscribe(Single.java:2703)
                                                                            at io.reactivex.internal.operators.single.SingleFlatMap.subscribeActual(SingleFlatMap.java:36)
                                                                            at io.reactivex.Single.subscribe(Single.java:2703)
                                                                            at io.reactivex.internal.operators.single.SingleToObservable.subscribeActual(SingleToObservable.java:34)
                                                                            at io.reactivex.Observable.subscribe(Observable.java:10842)
                                                                            at io.reactivex.internal.operators.observable.ObservableFlatMap.subscribeActual(ObservableFlatMap.java:55)
                                                                            at io.reactivex.Observable.subscribe(Observable.java:10842)
                                                                            at io.reactivex.internal.operators.observable.ObservableFlatMap.subscribeActual(ObservableFlatMap.java:55)
                                                                            at io.reactivex.Observable.subscribe(Observable.java:10842)
                                                                            at io.reactivex.internal.operators.observable.ObservableMap.subscribeActual(ObservableMap.java:33)
                                                                            at io.reactivex.Observable.subscribe(Observable.java:10842)
                                                                            at io.reactivex.internal.operators.observable.ObservableOnErrorNext.subscribeActual(ObservableOnErrorNext.java:38)
                                                                            at io.reactivex.Observable.subscribe(Observable.java:10842)
                                                                            at io.reactivex.internal.operators.observable.ObservableSubscribeOn$SubscribeTask.run(ObservableSubscribeOn.java:96)
                                                                            at io.reactivex.Scheduler$DisposeTask.run(Scheduler.java:452)
                                                                            at io.reactivex.internal.schedulers.ScheduledRunnable.run(ScheduledRunnable.java:61)
                                                                            at io.reactivex.internal.schedulers.ScheduledRunnable.call(ScheduledRunnable.java:52)
                                                                            at java.util.concurrent.FutureTask.run(FutureTask.java:237)
                                                                            at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:272)
                                                                            at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
                                                                            at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
                                                                            at java.lang.Thread.run(Thread.java:761)
                                                                         Caused by: io.reactivex.exceptions.CompositeException$CompositeExceptionCausalChain: Chain of Causes for CompositeException In Order Received =>
                                                                            at io.reactivex.plugins.RxJavaPlugins.onError(RxJavaPlugins.java:364)
06-12 11:25:51.532 32762-32762/com.ezlo.tracker.debug E/AndroidRuntime:     at io.reactivex.internal.functions.Functions$OnErrorMissingConsumer.accept(Functions.java:704)
                                                                            at io.reactivex.internal.functions.Functions$OnErrorMissingConsumer.accept(Functions.java:701)
                                                                            at io.reactivex.internal.observers.LambdaObserver.onError(LambdaObserver.java:74)
                                                                            at io.reactivex.internal.operators.observable.ObservableObserveOn$ObserveOnObserver.checkTerminated(ObservableObserveOn.java:276)
                                                                            at io.reactivex.internal.operators.observable.ObservableObserveOn$ObserveOnObserver.drainNormal(ObservableObserveOn.java:172)
                                                                            at io.reactivex.internal.operators.observable.ObservableObserveOn$ObserveOnObserver.run(ObservableObserveOn.java:252)
                                                                            at io.reactivex.android.schedulers.HandlerScheduler$ScheduledRunnable.run(HandlerScheduler.java:109)
                                                                            at android.os.Handler.handleCallback(Handler.java:751)
                                                                            at android.os.Handler.dispatchMessage(Handler.java:95)
                                                                            at android.os.Looper.loop(Looper.java:154)
                                                                            at android.app.ActivityThread.main(ActivityThread.java:6119)
                                                                            at java.lang.reflect.Method.invoke(Native Method)
                                                                            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:886)
                                                                            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:776)
                                                                         Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'android.content.res.XmlResourceParser android.content.pm.ProviderInfo.loadXmlMetaData(android.content.pm.PackageManager, java.lang.String)' on a null object reference
                                                                            at android.support.v4.content.FileProvider.parsePathStrategy(FileProvider.java:583)
                                                                            at android.support.v4.content.FileProvider.getPathStrategy(FileProvider.java:557)
                                                                            at android.support.v4.content.FileProvider.getUriForFile(FileProvider.java:399)
                                                                            at com.miguelbcr.ui.rx_paparazzo2.interactors.TakePhoto.getUri(TakePhoto.java:84)
                                                                            at com.miguelbcr.ui.rx_paparazzo2.interactors.TakePhoto.react(TakePhoto.java:53)
                                                                            at com.miguelbcr.ui.rx_paparazzo2.workers.Camera$3.apply(Camera.java:65)
                                                                            at com.miguelbcr.ui.rx_paparazzo2.workers.Camera$3.apply(Camera.java:63)
                                                                            at io.reactivex.internal.operators.observable.ObservableFlatMap$MergeObserver.onNext(ObservableFlatMap.java:121)
                                                                            at io.reactivex.internal.operators.single.SingleToObservable$SingleToObservableObserver.onSuccess(SingleToObservable.java:59)
                                                                            at io.reactivex.internal.operators.single.SingleFlatMap$SingleFlatMapCallback$FlatMapSingleObserver.onSuccess(SingleFlatMap.java:111)
                                                                            at io.reactivex.internal.operators.single.SingleJust.subscribeActual(SingleJust.java:30)
                                                                            at io.reactivex.Single.subscribe(Single.java:2703)
                                                                            at io.reactivex.internal.operators.single.SingleFlatMap$SingleFlatMapCallback.onSuccess(SingleFlatMap.java:84)
                                                                            at io.reactivex.internal.operators.observable.ObservableToListSingle$ToListObserver.onComplete(ObservableToListSingle.java:113)
                                                                            at io.reactivex.observers.SerializedObserver.onComplete(SerializedObserver.java:181)
                                                                            at io.reactivex.internal.operators.observable.ObservableConcatMap$SourceObserver.drain(ObservableConcatMap.java:205)
                                                                            at io.reactivex.internal.operators.observable.ObservableConcatMap$SourceObserver.onComplete(ObservableConcatMap.java:148)
                                                                            at io.reactivex.internal.operators.observable.ObservableFlattenIterable$FlattenIterableObserver.onComplete(ObservableFlattenIterable.java:134)
                                                                            at io.reactivex.internal.operators.observable.ObservableBuffer$BufferExactObserver.onComplete(ObservableBuffer.java:134)
                                                                            at io.reactivex.internal.operators.observable.ObservableFlatMap$MergeObserver.drainLoop(ObservableFlatMap.java:367)
                                                                            at io.reactivex.internal.operators.observable.ObservableFlatMap$MergeObserver.drain(ObservableFlatMap.java:323)
                                                                            at io.reactivex.internal.operators.observable.ObservableFlatMap$MergeObserver.onComplete(ObservableFlatMap.java:300)
                                                                            at io.reactivex.internal.operators.observable.ObservableFlatMap$MergeObserver.drainLoop(ObservableFlatMap.java:367)
                                                                            at io.reactivex.internal.operators.observable.ObservableFlatMap$MergeObserver.drain(ObservableFlatMap.java:323)
06-12 11:25:51.532 32762-32762/com.ezlo.tracker.debug E/AndroidRuntime:     at io.reactivex.internal.operators.observable.ObservableFlatMap$MergeObserver.onComplete(ObservableFlatMap.java:300)
                                                                            at io.reactivex.internal.operators.observable.ObservableFromArray$FromArrayDisposable.run(ObservableFromArray.java:110)
                                                                            at io.reactivex.internal.operators.observable.ObservableFromArray.subscribeActual(ObservableFromArray.java:36)
                                                                            at io.reactivex.Observable.subscribe(Observable.java:10842)
                                                                            at io.reactivex.internal.operators.observable.ObservableFlatMap.subscribeActual(ObservableFlatMap.java:55)
                                                                            at io.reactivex.Observable.subscribe(Observable.java:10842)
                                                                            at io.reactivex.internal.operators.observable.ObservableFlatMap.subscribeActual(ObservableFlatMap.java:55)
                                                                            at io.reactivex.Observable.subscribe(Observable.java:10842)
                                                                            at io.reactivex.internal.operators.observable.ObservableBuffer.subscribeActual(ObservableBuffer.java:44)
                                                                            at io.reactivex.Observable.subscribe(Observable.java:10842)
                                                                            at io.reactivex.internal.operators.observable.ObservableFlattenIterable.subscribeActual(ObservableFlattenIterable.java:44)
                                                                            at io.reactivex.Observable.subscribe(Observable.java:10842)
                                                                            at io.reactivex.internal.operators.observable.ObservableConcatMap.subscribeActual(ObservableConcatMap.java:52)
                                                                            at io.reactivex.Observable.subscribe(Observable.java:10842)
                                                                            at io.reactivex.internal.operators.observable.ObservableToListSingle.subscribeActual(ObservableToListSingle.java:58)
                                                                            at io.reactivex.Single.subscribe(Single.java:2703)
                                                                            at io.reactivex.internal.operators.single.SingleFlatMap.subscribeActual(SingleFlatMap.java:36)
                                                                            at io.reactivex.Single.subscribe(Single.java:2703)
                                                                            at io.reactivex.internal.operators.single.SingleToObservable.subscribeActual(SingleToObservable.java:34)
                                                                            at io.reactivex.Observable.subscribe(Observable.java:10842)
                                                                            at io.reactivex.internal.operators.observable.ObservableFlatMap.subscribeActual(ObservableFlatMap.java:55)
                                                                            at io.reactivex.Observable.subscribe(Observable.java:10842)
                                                                            at io.reactivex.internal.operators.observable.ObservableFlatMap.subscribeActual(ObservableFlatMap.java:55)
                                                                            at io.reactivex.Observable.subscribe(Observable.java:10842)
                                                                            at io.reactivex.internal.operators.observable.ObservableMap.subscribeActual(ObservableMap.java:33)
                                                                            at io.reactivex.Observable.subscribe(Observable.java:10842)
                                                                            at io.reactivex.internal.operators.observable.ObservableOnErrorNext.subscribeActual(ObservableOnErrorNext.java:38)
                                                                            at io.reactivex.Observable.subscribe(Observable.java:10842)
                                                                            at io.reactivex.internal.operators.observable.ObservableSubscribeOn$SubscribeTask.run(ObservableSubscribeOn.java:96)
                                                                            at io.reactivex.Scheduler$DisposeTask.run(Scheduler.java:452)
                                                                            at io.reactivex.internal.schedulers.ScheduledRunnable.run(ScheduledRunnable.java:61)
                                                                            at io.reactivex.internal.schedulers.ScheduledRunnable.call(ScheduledRunnable.java:52)
                                                                            at java.util.concurrent.FutureTask.run(FutureTask.java:237)
                                                                            at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:272)
                                                                            at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
                                                                            at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
                                                                            at java.lang.Thread.run(Thread.java:761)
06-12 11:25:51.533 32762-32762/com.ezlo.tracker.debug D/Error: ERR: exClass=java.lang.NullPointerException
06-12 11:25:51.533 32762-32762/com.ezlo.tracker.debug D/Error: ERR: exMsg=Attempt to invoke virtual method 'android.content.res.XmlResourceParser android.content.pm.ProviderInfo.loadXmlMetaData(android.content.pm.PackageManager, java.lang.String)' on a null object reference
06-12 11:25:51.533 32762-32762/com.ezlo.tracker.debug D/Error: ERR: file=FileProvider.java
06-12 11:25:51.533 32762-32762/com.ezlo.tracker.debug D/Error: ERR: class=android.support.v4.content.FileProvider
06-12 11:25:51.533 32762-32762/com.ezlo.tracker.debug D/Error: ERR: method=parsePathStrategy line=583
06-12 11:25:51.533 32762-32762/com.ezlo.tracker.debug D/Error: ERR: stack=io.reactivex.exceptions.OnErrorNotImplementedException: 1 exceptions occurred. 
                                                                   at io.reactivex.internal.functions.Functions$OnErrorMissingConsumer.accept(Functions.java:704)
                                                                   at io.reactivex.internal.functions.Functions$OnErrorMissingConsumer.accept(Functions.java:701)
                                                                   at io.reactivex.internal.observers.LambdaObserver.onError(LambdaObserver.java:74)
                                                                   at io.reactivex.internal.operators.observable.ObservableObserveOn$ObserveOnObserver.checkTerminated(ObservableObserveOn.java:276)
                                                                   at io.reactivex.internal.operators.observable.ObservableObserveOn$ObserveOnObserver.drainNormal(ObservableObserveOn.java:172)
                                                                   at io.reactivex.internal.operators.observable.ObservableObserveOn$ObserveOnObserver.run(ObservableObserveOn.java:252)
                                                                   at io.reactivex.android.schedulers.HandlerScheduler$ScheduledRunnable.run(HandlerScheduler.java:109)
                                                                   at android.os.Handler.handleCallback(Handler.java:751)
                                                                   at android.os.Handler.dispatchMessage(Handler.java:95)
                                                                   at android.os.Looper.loop(Looper.java:154)
                                                                   at android.app.ActivityThread.main(ActivityThread.java:6119)
                                                                   at java.lang.reflect.Method.invoke(Native Method)
                                                                   at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:886)
                                                                   at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:776)
                                                                Caused by: io.reactivex.exceptions.CompositeException: 1 exceptions occurred. 
                                                                   at io.reactivex.internal.operators.observable.ObservableOnErrorNext$OnErrorNextObserver.onError(ObservableOnErrorNext.java:94)
                                                                   at io.reactivex.internal.observers.BasicFuseableObserver.onError(BasicFuseableObserver.java:100)
                                                                   at io.reactivex.internal.operators.observable.ObservableFlatMap$MergeObserver.checkTerminate(ObservableFlatMap.java:495)
                                                                   at io.reactivex.internal.operators.observable.ObservableFlatMap$MergeObserver.drainLoop(ObservableFlatMap.java:331)
                                                                   at io.reactivex.internal.operators.observable.ObservableFlatMap$MergeObserver.drain(ObservableFlatMap.java:323)
                                                                   at io.reactivex.internal.operators.observable.ObservableFlatMap$MergeObserver.onError(ObservableFlatMap.java:288)
                                                                   at io.reactivex.internal.operators.observable.ObservableFlatMap$MergeObserver.checkTerminate(ObservableFlatMap.java:495)
                                                                   at io.reactivex.internal.operators.observable.ObservableFlatMap$MergeObserver.drainLoop(ObservableFlatMap.java:331)
                                                                   at io.reactivex.internal.operators.observable.ObservableFlatMap$MergeObserver.drain(ObservableFlatMap.java:323)
                                                                   at io.reactivex.internal.operators.observable.ObservableFlatMap$MergeObserver.onError(ObservableFlatMap.java:288)
                                                                   at io.reactivex.internal.operators.observable.ObservableFlatMap$MergeObserver.onNext(ObservableFlatMap.java:125)
                                                                   at io.reactivex.internal.operators.single.SingleToObservable$SingleToObservableObserver.onSuccess(SingleToObservable.java:59)
                                                                   at io.reactivex.internal.operators.single.SingleFlatMap$SingleFlatMapCallback$FlatMapSingleObserver.onSuccess(SingleFlatMap.java:111)
                                                                   at io.reactivex.internal.operators.single.SingleJust.subscribeActual(SingleJust.java:30)
                                                                   at io.reactivex.Single.subscribe(Single.java:2703)
                                                                   at io.reactivex.internal.operators.single.SingleFlatMap$SingleFlatMapCallback.onSuccess(SingleFlatMap.java:84)
                                                                   at io.reactivex.internal.operators.observable.ObservableToListSingle$ToListObserver.onComplete(ObservableToListSingle.java:113)
                                                                   at io.reactivex.observers.SerializedObserver.onComplete(SerializedObserver.java:181)
                                                                   at io.reactivex.internal.operators.observable.ObservableConcatMap$SourceObserver.drain(ObservableConcatMap.java:205)
                                                                   at io.reactivex.internal.operators.observable.ObservableConcatMap$SourceObserver.onComplete(ObservableConcatMap.java:148)
                                                                   at io.reactivex.internal.operators.observable.ObservableFlattenIterable$FlattenIterableObserver.onComplete(ObservableFlattenIterable.java:134)
                                                                   at io.reactivex.internal.operators.observable.ObservableBuffer$BufferExactObserver.onComplete(ObservableBuffer.java:134)
                                                                   at io.reactivex.internal.operators.observable.ObservableFlatMap$MergeObserver.drainLoop(ObservableFlatMap.java:367)
                                                               	at io.reactivex.internal.operators.observable.ObservableFlatMap$MergeObserver.drain(Obse`

**Comment by miguelbcr** [comment]
Hi @ZBlaZe2 !
- What RxPaparazzo version are you using?
- Are you using any custom FileProvider in your Manifest.xml?
- If yes, have you set this property `setFileProviderAuthority` in the builder `RxPaparazzo.register(this)` ?

**Comment by ZBlaZe2** [comment]
Hi @miguelbcr !

- Version is 0.5.3-2.x
- I don't use custom FileProvider in this project yet

**Comment by miguelbcr** [comment]
Hi @ZBlaZe2 ,
sorry for the late
I think your problem is that you forgot to add this to your manifest:
```xml
<provider
            android:name="android.support.v4.content.FileProvider"
            android:authorities="${applicationId}.file_provider"
            android:exported="false"
            android:grantUriPermissions="true">
            <meta-data
                android:name="android.support.FILE_PROVIDER_PATHS"
                android:resource="@xml/rx_paparazzo_file_paths"/>
        </provider>
``` 
Please read the [README.md](https://github.com/miguelbcr/RxPaparazzo#usage) carefully.
Let me know if it works for you, thanks!
