### ISSUE TITLE
Add mime type for single file picker get error in android version below kitkat

### ISSUE THREAD

**Issue by erfanegtfi** [miguelbcr/RxPaparazzo#93]
After add mime type for single file picker get error. Just in android version below kitkat,
file picker doesn't open

**Comment by miguelbcr** [comment]
Hi @erfanegtfi !
could you post the error you get and the piece of code where you are calling to RxPaparazzo with the mimeType?

**Comment by erfanegtfi** [comment]
Hi, I use library sample app
After press 'Pdf and images files' button run in genymotion note 2 sdk version 18
Other features work fine.

`	android.content.ActivityNotFoundException: No Activity found to handle Intent { act=android.intent.action.GET_CONTENT (has extras) }
        at android.app.Instrumentation.checkStartActivityResult(Instrumentation.java:1632)
        at android.app.Instrumentation.execStartActivity(Instrumentation.java:1424)
        at android.app.Activity.startActivityForResult(Activity.java:3390)
        at android.app.Activity.startActivityForResult(Activity.java:3351)
        at rx_activity_result2.HolderActivity.onCreate(HolderActivity.java:57)
        at android.app.Activity.performCreate(Activity.java:5133)
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1087)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2175)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2261)
        at android.app.ActivityThread.access$600(ActivityThread.java:141)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1256)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loop(Looper.java:137)
        at android.app.ActivityThread.main(ActivityThread.java:5103)
        at java.lang.reflect.Method.invokeNative(Native Method)
        at java.lang.reflect.Method.invoke(Method.java:525)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:737)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:553)
        at dalvik.system.NativeStart.main(Native Method)`

**Comment by erfanegtfi** [comment]
I think you can fix it if add below pieces of code in [PickFile.java](https://github.com/miguelbcr/RxPaparazzo/blob/2.x/rx_paparazzo/src/main/java/com/miguelbcr/ui/rx_paparazzo2/interactors/PickFile.java#L61) and [PickFiles.java](https://github.com/miguelbcr/RxPaparazzo/blob/2.x/rx_paparazzo/src/main/java/com/miguelbcr/ui/rx_paparazzo2/interactors/PickFiles.java#L91) method getFileChooserIntent()

for sdk below kitkat this work:
`String[] mimeTypes = config.getMultipleMimeTypes();
StringBuilder types= new StringBuilder();
for (int i = 0; i <mimeTypes.length ; i++) {
     types.append(mimeTypes[i]);
     types.append("|");
}
intent.setType(types.toString());`

**Comment by miguelbcr** [comment]
Actually, it is not an unhandled error, it is being handled, for instance, in `SampleActivity.java`:
```
private void processSingle(Observable<Response<SampleActivity, FileData>> pickUsingGallery) {
        pickUsingGallery
                .subscribeOn(Schedulers.io())
                .observeOn(AndroidSchedulers.mainThread())
                .subscribe(response -> {
                    if (PickerUtil.checkResultCode(SampleActivity.this, response.resultCode())) {
                        response.targetUI().loadImage(response.data());
                    }
                }, throwable -> {
                    throwable.printStackTrace();
   HERE ->          Toast.makeText(getApplicationContext(), "ERROR " + throwable.getMessage(), Toast.LENGTH_SHORT).show();
                });
    } 
```

The error message says `No Activity found to handle Intent { act=android.intent.action.GET_CONTENT (has extras) }`, It is because there is no a File Browser installed on the device. So, you should encourage to the user to use a File Browser in order to pick up other files such as PDF rather than images.

Your solution works in the sample app because there are serveral mimeTypes (images and PDFs), so the app opens the Gallery app, but if you force to only pick PDF files up (as I've done on the left button `Pdf and images file` as you can see in the below GIF), you will get the same error.

![rxpaparazzo](https://user-images.githubusercontent.com/2734557/45748641-a98b3400-bc09-11e8-93a2-3aba9c1199ec.gif)

On the other hand, I guess it is not usual on real devices, where it is supposed to have a File Browser installed

**Comment by miguelbcr** [comment]
Closing it... feel free to open it if you have more questions
